Upgrade to FGT helm chart v0.2.0 - Updated readme and example configuration
PharmaLedger-IMI/helm-charts pull request #91
Opened 2022-05-12 16:03 UTC by lukasosterheider

=> Readme and example configuration file changes only.

2022-05-12 16:05 UTC, lukasosterheider commented
Will work on the secret detection issue tomorrow.

2022-05-16 07:57 UTC, lukasosterheider commented
@tgip-work : Hi Torsten, just readme and example config changes. Please approve and merge.
Thank you!

2022-05-20 12:10 UTC, tgip-work requested changes
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md.gotmpl
> +    helm upgrade my-release-name your-container-registry/fgt --version={{ template "chart.version" . }} \
Hi Lukas,

the repo for the helm charts is still `pharmaledger-imi`

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md.gotmpl
> +    helm upgrade my-release-name your-container-registry/fgt --version={{ template "chart.version" . }} \
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md.gotmpl
> +    helm upgrade my-release-name your-container-registry/fgt --version={{ template "chart.version" . }} \
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md
> +    helm upgrade my-release-name your-container-registry/fgt --version=0.2.0 \
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md
> +    helm upgrade my-release-name your-container-registry/fgt --version=0.2.0 \
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 12:10 UTC, tgip-work commented on charts/fgt/README.md
> +    helm upgrade my-release-name your-container-registry/fgt --version=0.2.0 \
Hi Lukas,

the repo for the helm charts is still pharmaledger-imi

2022-05-20 19:05 UTC, tgip-work approved these changes

2022-05-20 19:06 UTC, merged